### ISSUE TITLE
Artist credit: Jazzy Siy/Jazz Siy

### ISSUE THREAD

**Issue by kunim0n** [Oracle-of-the-Void/ootv-client#118]
Chagatai's Wrath (AM, 1) has "Jazzy Siy" as the listed artist. That's what the credit says. However this is the only art by Jazzy. On the other hand, there are other 15 cards credited to "Jazz Siy" so this seems to be just a typo.

**Comment by MacBeth2001** [comment]
Corrected and Note on misspelling added.
