### ISSUE TITLE
Artist credit: Legulu's Legion (AM, 84)

### ISSUE THREAD

**Issue by kunim0n** [Oracle-of-the-Void/ootv-client#119]
Credit is corrected as: "Brent Chumely (Mislabeled as Nikolay Stoyanov)". However, clicking the link searches for the whole text, instead of just "Brent Chumley" and, consequently, finds just this one card.

**Comment by MacBeth2001** [comment]
Chumley spelling corrected and correction changed to be a separate Note to fix link.
