### ISSUE TITLE
Shiba Aikune Exp3 (Samurai Edition Banzai) wrongly credited

### ISSUE THREAD

**Issue by OninoPikachu** [Oracle-of-the-Void/ootv-client#132]
Shiba Aikune Experienced 3 (Samurai Edition Banzai) https://www.oracleofthevoid.com/#game=l5r,#cardid=6737 is wrongly credited to April Lee. Art is from William O'Connor, as credited for same card of Khan's Defiance. Check card for reference.

**Comment by MacBeth2001** [comment]
Corrected
