### ISSUE TITLE
Karl Christensen is wrong, it should be Kari Christensen

### ISSUE THREAD

**Issue by OninoPikachu** [Oracle-of-the-Void/ootv-client#133]
All the cards credited to Karl Christensen should be credited to Kari Christensen. The "L" has been missread from the cards, it is an "I". Cards are Isawa Kyoko (from War of Honor set only, the other two are Ok), By Steel Redeemed, Doji Domotai (DE & LE, TG2 is Ok), Doji Domotai Exp3 (both versions), Ransom Hostage, Togashi Teijo, and Unspoken Threats (H&E only, SE is Ok).

**Comment by MacBeth2001** [comment]
Corrected.
