### ISSUE TITLE
Echoes of Disgrace misscredited card on CE

### ISSUE THREAD

**Issue by OninoPikachu** [Oracle-of-the-Void/ootv-client#137]
Echoes of Disgrace https://www.oracleofthevoid.com/#game=l5r,#cardid=2277 was misscredited to Veronica Jones in Celestial Edition card, instead to Heather Kreiter.

For reference check Echoes of Disgrace for The Truest Test and Samurai Edition sets.

**Comment by MacBeth2001** [comment]
CE card corrected to Heather and note added.
