### ISSUE TITLE
Additional Format Legality

### ISSUE THREAD

**Issue by Shadeblade11** [Oracle-of-the-Void/ootv-client#15]
A request for another format filter for the modern format, as shown on this forum
http://l5rmodern.roku-mart.com/viewtopic.php?f=2&t=2
Due to how expensive the format is in set length, a format filter would be very helpful to be able to build better decks for the format.

**Comment by ksuquix** [comment]
This is in progress.   I'll probably fall asleep before the script is done processing them all :)

**Comment by ksuquix** [comment]
Done!  Log out and back in if you don't see Modern as a legality.
