### ISSUE TITLE
Select boxes not loading correctly probably because of rawgit CDN issue

### ISSUE THREAD

**Issue by renecum** [Oracle-of-the-Void/ootv-client#155]
The lists are not loading correctly. See the picture below.

**To Reproduce**

1. Reload the site without cache:
2. You'll see that the lists are not showing as they were before, loading with no styles.

**Expected behavior**
Lists should load with fonts, allow type names, and filter items for easy selection.

**Screenshots**

![cdn timout](https://user-images.githubusercontent.com/670045/187011076-f0abb3f2-99a0-4d66-8c95-a8a5ab8c69b0.jpg)

**Desktop:**
 - OS: macOS
 - Browser: chorme, safari
 - Version: 

**Additional context**
[Rawgit](https://rawgit.com/) has reached the end of its useful life since October 8, 2018; it is suggested to find a replacement.

**Comment by ksuquix** [comment]
a redirect in rawgit was put in place soon after this ticket was created.    I've now changed it to jsdelivr, so should be fine for awhile.
