### ISSUE TITLE
Doji Tanitsu Exp 3 listed as gold Legal

### ISSUE THREAD

**Issue by renecumcignium** [Oracle-of-the-Void/ootv-client#166]
[Doji Tanitsu Exp 3](https://oracleofthevoid.com/#game=l5r,#cardid=2163) is showing as gold legal when I filter but I don't see a printed version with the gold kanji.

![tanintsu-not-gold-legal](https://github.com/Oracle-of-the-Void/ootv-client/assets/39271808/dd095f85-1cb1-43e7-b6dd-9e15aedf46c4)

**Comment by MacBeth2001** [comment]
Corrected.
