### ISSUE TITLE
cardid 10613 - Imperial Explorer's Dojo missing Imperial keyword

### ISSUE THREAD

**Issue by Kwekachu** [Oracle-of-the-Void/ootv-client#167]
![image](https://github.com/Oracle-of-the-Void/ootv-client/assets/68788303/85d62c18-b392-41ce-b63d-eeaec14a035a)

As the title mentions, oracle wording is missing the Imperial keyword present on the card

**Comment by MacBeth2001** [comment]
Corrected.
