### ISSUE TITLE
Decklist isn't being saved for future sessions

### ISSUE THREAD

**Issue by Azarack** [Oracle-of-the-Void/ootv-client#168]
**Describe the bug**
I have been working on a deck using the decklist feature.  All cards I add will stay in the list, but the numbers/amount of each card wont update.  The numbers stay at a previous iteration of the list which I have tried to update multiple times.

**To Reproduce**
1. Go to directory tab and create a list
2. Populate list with cards and set an amount for each to be in a deck
3. Wait a day
4. Update list with new cards/different amounts of previous cards
5. Wait a day
6. See list is in previous version/amounts

**Expected behavior**
When making changes to a list they should be saved and the newest version should be what is displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 123.0.6312.124 (Official Build) (64-bit)

**Additional context**

**Comment by ksuquix** [comment]
What's your UID?  (hover your name in the upper right corner).

Also: I might have just fixed an issue recently that dealt with this.  Are you still having problems?

**Comment by Azarack** [comment]
My UID is 46720.  I just made an update to one of my decklists and will check tomorrow and see if the issue is still there.

**Comment by Azarack** [comment]
It appears the issue has been fixed.  The list I edited a few days ago still shows the edited amounts.

**Comment by ksuquix** [comment]
ok.  going to mark this as being due to AWS lambda updates.
