### ISSUE TITLE
Deck Not Loading - b.deck undefined error due to Nakanu's Creations proxy

### ISSUE THREAD

**Issue by Devurauxe** [Oracle-of-the-Void/ootv-client#171]
**Describe the bug**
For whatever reason, the site is getting a "b.deck is undefined" error whenever it tried to load a deck containing the Nakanu's Creations proxy.

**To Reproduce**
1. Create a new decklist
2. Add Nakanu's Creations to the deck
3. Attempt to open the deck and view it, noting the error code thrown and the inability to open or even download

**Expected behavior**
I expected the deck to open for further editing

**Comment by Devurauxe** [comment]
This bug seems to also be occurring when adding "Suiteru's Podling" to a deck (followers created by Suiteru no Oni)

**Comment by Devurauxe** [comment]
Double update, it seems like a lot of tokens are causing this issue. We have also found it happening with Emerald Magistrate.

**Comment by ksuquix** [comment]
looks like several of the tokens didn't have a deck type defined:
Did this search:
-deck:other -deck:dynasty -deck:pre-game -deck:fate

Then added this to all of them:
  "deck": [
    "Other"
  ],

Should be good now.
