### ISSUE TITLE
PDF Printing blocked by CORS policy

### ISSUE THREAD

**Issue by hazzler** [Oracle-of-the-Void/ootv-client#24]
Got this from the browser console log when trying to export to PDF

Access to Image at 'https://images.oracleofthevoid.com/l5r/5b/96/printing_3_1_details.jpg' from origin 'https://preview.oracleofthevoid.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://preview.oracleofthevoid.com' is therefore not allowed access.

**Comment by ksuquix** [comment]
Dropping here for later, but this is what's happening.    If I don't get it fixed in a bit, clearing your cache should make it work (on an ad-hoc basis).

https://serverfault.com/questions/856904/chrome-s3-cloudfront-no-access-control-allow-origin-header-on-initial-xhr-req/856948#856948
