### ISSUE TITLE
Cards with missing Onyx legality

### ISSUE THREAD

**Issue by kempynezumi** [Oracle-of-the-Void/ootv-client#46]
Following cards have printings (as 20F promos) with black/onyx kanji but don't have Onyx legality in Oracle:

A Prophet Revealed
Doom of the Dark Lord
Shadow of the Dark God
Berserkers
Scout
Zombie Troops
Another Time
Brilliant Victory
Corrupted Ground
Duty
Narrow Ground
Shadowlands Sickness

**Comment by ksuquix** [comment]
done
