### ISSUE TITLE
Warlord

### ISSUE THREAD

**Issue by akodoraikitsu** [Oracle-of-the-Void/ootv-client#68]
Really appreciate the updates to Oracle to include 7th Sea, LBS, and Initial D. Any chance we will see Warlord CCG added or other AEG CCGs?

**Comment by ksuquix** [comment]
I intend to add Warlord, Spycraft and Doomtown at least.... as well as non-AEG games.   If you have good resources for full databases/images, PLEASE hop on discord and point me at them.   Most of the initial work is finding good sources along with a few dozen hours each of massaging them into usable form.
